redo, up to configuration options

diff --git a/installerconfig_tmp2 b/installerconfig_tmp2
--- a/installerconfig_tmp2
+++ b/installerconfig_tmp2
@@ -359,9 +359,38 @@ ha_info ()
 }
 
 
+# Determine
+check_auto_install ()
+{
+	if [ -f /etc/auto_install_config ] && [ -s /etc/auto_install_config ]; then
+		return 1
+	else
+		return 0
+	fi
+}
+
+return_answer ()
+{
+	return $1
+}
+
 #
 # Set variables for install
 #
+
+# Set variables for auto_install
+check_auto_install
+AUTO_INSTALL=$?
+
+if [ $AUTO_INSTALL -eq 1 ]; then
+	IFS="="
+	while read -r name value
+	do
+		eval $name=\$value
+	done < /etc/auto_install_config
+	IFS=$' \t\n'
+fi
+
 
 # Statseeker root directory
 ROOT_DIR=/usr/local/statseeker
@@ -461,10 +490,14 @@ of parity RAID is up to 15 times slower than a single disk or a
 stripe/mirror RAID setup. As the Statseeker databases grow in
 size, data loss WILL occur in a RAID 5 & 6 setup.'
 
-dialog --title "Welcome to Statseeker" \
-       --yes-label "Continue Install" \
-       --no-label "Reboot" \
-       --yesno "${message}" 20 70
+if [ $AUTO_INSTALL -ne 1 ]; then
+	dialog --title "Welcome to Statseeker" \
+	       --yes-label "Continue Install" \
+	       --no-label "Reboot" \
+	       --yesno "${message}" 20 70
+else
+	return_answer 0
+fi
 
 if [ $? -ne 0 ]; then
    reboot
@@ -522,7 +555,11 @@ done
 # Check that at least one disk was found
 #
 if [ $CNT -eq 0 ]; then
-   dialog --msgbox "\n      !!! Could not find a valid disk for Statseeker install !!!" 7 75
+	if [ $AUTO_INSTALL -ne 1 ]; then
+		dialog --msgbox "\n      !!! Could not find a valid disk for Statseeker install !!!" 7 75
+	else
+		echo "\n      !!! Could not find a valid disk for Statseeker install !!!"
+	fi
    abort
 fi
 
@@ -542,11 +579,15 @@ fi
 #
 if [ ${CNT} -gt 1 ]; then
    exec 3>&1
-   disk_dev=`echo "${disk_list}" | xargs dialog \
-      --backtitle 'FreeBSD Installer' \
-      --title 'Installation Disk Selection' \
-      --menu 'Choose the disk where you would like Statseeker installed:' \
-      0 0 0 2>&1 1>&3`
+	if [ $AUTO_INSTALL -ne 1 ]; then
+		disk_dev=`echo "${disk_list}" | xargs dialog \
+			--backtitle 'FreeBSD Installer' \
+			--title 'Installation Disk Selection' \
+			--menu 'Choose the disk where you would like Statseeker installed:' \
+			0 0 0 2>&1 1>&3`
+	else
+		disk_dev=`echo "${disk_list}" | head -n1 | cut -d " " -f1`
+	fi
    [ $? -eq 1 ] && abort
    exec 3>&-
    disk_size=`diskinfo ${disk_dev} | awk '{ print $4; }'`
@@ -568,8 +609,12 @@ if [ $disk_size -lt $check_size ]; then
    GB_disk_size=$(($disk_size/2/1024/1024))
    GB_check_size=$(($check_size/2/1024/1024))
 
-   dialog --msgbox " !!! You must have at least $GB_check_size GB of storage to install statseeker !!!  \n\nYou only have $GB_disk_size GB of storage. \n\nPlease increase your storage size." 10 75
-   abort
+	if [ $AUTO_INSTALL -ne 1 ]; then
+		dialog --msgbox " !!! You must have at least $GB_check_size GB of storage to install statseeker !!!  \n\nYou only have $GB_disk_size GB of storage. \n\nPlease increase your storage size." 10 75
+	else
+		echo " !!! You must have at least $GB_check_size GB of storage to install statseeker !!!  \n\nYou only have $GB_disk_size GB of storage. \n\nPlease increase your storage size." 
+	fi
+	abort
 fi
 
 #
@@ -687,7 +732,11 @@ if [ $do_partition -eq 1 ]; then
          ssversion=`cat /mnt/${ssfile}`
 
          # Prompt the user to retain network config
-         dialog --yesno "                       !!! IMPORTANT !!!\nPlease ensure you have a valid backup before Upgrading Statseeker.\nIf you are upgrading and do not have a valid backup please power\noff the server now.\n\nDANGER This Statseeker upgrade requires changes to hard disk partitions. All data on the hard disk will be destroyed.\nWould you like to retain your existing system network configuration before upgrading?\n\n" 13 70
+			if [ $AUTO_INSTALL -ne 1 ]; then
+				dialog --yesno "                       !!! IMPORTANT !!!\nPlease ensure you have a valid backup before Upgrading Statseeker.\nIf you are upgrading and do not have a valid backup please power\noff the server now.\n\nDANGER This Statseeker upgrade requires changes to hard disk partitions. All data on the hard disk will be destroyed.\nWould you like to retain your existing system network configuration before upgrading?\n\n" 13 70
+			else
+				return_answer $auto_retain_network
+			fi
 
          if [ $? -eq 0 ]; then
             checkversion $ssversion 5.0.0
@@ -729,7 +778,11 @@ if [ $do_partition -eq 0 ]; then
       ssversion=`cat /mnt/${ssfile}`
 
       # Prompt the user to retain their data
-      dialog --yesno "                       !!! IMPORTANT !!!\nPlease ensure you have a valid backup before Upgrading Statseeker.\nIf you are upgrading and do not have a valid backup please power\noff the server now.\n\nThis disk contains an existing Statseeker installation:\n v${ssversion}\n\nWould you like to keep the existing configuration and data?" 13 70
+		if [ $AUTO_INSTALL -ne 1 ]; then
+			dialog --yesno "                       !!! IMPORTANT !!!\nPlease ensure you have a valid backup before Upgrading Statseeker.\nIf you are upgrading and do not have a valid backup please power\noff the server now.\n\nThis disk contains an existing Statseeker installation:\n v${ssversion}\n\nWould you like to keep the existing configuration and data?" 13 70
+		else
+			return_answer $auto_retain_data
+		fi
 
       if [ $? -eq 0 ]; then
          do_partition=0
@@ -753,10 +806,14 @@ fi
 # Do the disk partitioning
 #
 if [ $do_partition -eq 1 ]; then
+	
+	if [ $AUTO_INSTALL -ne 1 ]; then
+		dialog --yesno "                 DANGER\n\nAll data on the hard disk will be destroyed.\n\n         Do you wish to continue ?\n" 10 50 || abort
 
-   dialog --yesno "                 DANGER\n\nAll data on the hard disk will be destroyed.\n\n         Do you wish to continue ?\n" 10 50 || abort
-
-   dialog --infobox "Partitioning hard disk" 3 70
+		dialog --infobox "Partitioning hard disk" 3 70
+	else
+		echo "Partitioning hard disk"
+	fi
 
    #
    # Wipe the first meg of data off the disk. This will get rid
@@ -1311,11 +1368,19 @@ gpart unset -a 'bootme' -i ${os_oth_index} ${disk_dev} >> ${logfile} || abort
 #
 # Create newfs partitions
 #
-dialog --infobox "Creating / filesystem..." 3 70
+if [ $AUTO_INSTALL -ne 1 ]; then
+	dialog --infobox "Creating / filesystem..." 3 70
+else:
+	echo "Creating / filesystem..."
+fi
 newfs "${label_dir}/${os_new}" >> ${logfile} || abort
 
 if [ $do_partition -eq 1 ]; then
-   dialog --infobox "Creating /home filesystem..." 3 70
+	if [ $AUTO_INSTALL -ne 1 ]; then
+		dialog --infobox "Creating /home filesystem..." 3 70
+	else
+		echo "Creating /home filesystem..."
+	fi
    newfs $home_newfs_opts "${label_dir}/${data_label}" >> ${logfile} || abort
 fi
 
@@ -1425,9 +1490,17 @@ fi
 #
 # Install the base and kernel distributions
 #
-dialog --infobox "Installing operating system files. Please wait...." 3 70
+if [ $AUTO_INSTALL -ne 1 ]; then
+	dialog --infobox "Installing operating system files. Please wait...." 3 70
+else
+	echo "Installing operating system files. Please wait...."
+fi
 tar -xf /usr/freebsd-dist/base.txz -C /mnt || abort
-dialog --infobox "Installing kernel. Please wait...." 3 70
+if [ $AUTO_INSTALL -ne 1 ]; then
+	dialog --infobox "Installing kernel. Please wait...." 3 70
+else
+	echo "Installing kernel. Please wait...."
+fi
 tar -xf /usr/freebsd-dist/kernel.txz -C /mnt || abort
 
 
